AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aspire-sam

  SAM Template for Cognito

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: 'Aspire-Dev'
  Env:
    Type: String
    Default: "dev"
    AllowedValues : ["dev", "prod"]
  AspireDbLibVersion:
    Type: Number
    Default: 1

Globals:
  Function:
    Runtime: python3.6
    Timeout: 30

Resources:
  AspireUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: 'verified_email'
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          TemporaryPasswordValidityDays: 7
      Schema:
        - Mutable: true
          Name: 'given_name'
          Required: true
        - Mutable: true
          Name: 'family_name'
          Required: true
        - Mutable: true
          Name: 'phone_number'
          Required: false
        - Mutable: true
          Name: 'address'
          Required: true
        - Mutable: true
          Name: 'gender'
          Required: true
        - Mutable: true
          Name: 'picture'
          Required: false
        - Mutable: true
          Name: 'birthdate'
          Required: true
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'prefix'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'industry'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'industry_tags'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'position'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'company'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'education_level'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'resume'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'linkedin'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'credits'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'user_type'
        - AttributeDataType: 'Number'
          Mutable: true
          Name: 'start_date'
        - AttributeDataType: 'Number'
          Mutable: true
          Name: 'end_date'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'declared_chats_freq'
        - AttributeDataType: 'String'
          Mutable: true
          Name: 'remaining_chats_freq'
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      UserPoolName: !Ref CognitoUserPoolName

  # TODO: CognitoPostConfAdminPolicy resource should be AspireUserPool.Arn
  CognitoPostConfirmation:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: PostConfirmation
      Handler: lambda_function.handler
      Policies:
        - Statement:
          - Sid: CognitoPostConfSESSendPolicy
            Effect: Allow
            Action:
              - ses:SendEmail
              - ses:SendRawEmail
            Resource: '*'
        - Statement:
          - Sid: CognitoPostConfAdminPolicy
            Effect: Allow
            Action:
              - cognito-idp:AdminDisableUser
            Resource: '*'
      Events:
        CognitoPostConfirmationEvent:
          Type: Cognito
          Properties:
            UserPool: !Ref AspireUserPool
            Trigger: PostConfirmation
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:max-aspire-database-${Env}-:${AspireDbLibVersion}'
      

Outputs:
  AspireUserPoolId:
    Description: 'Cognito User Pool Id'
    Value: !Ref AspireUserPool

  AspireUserPoolArn:
    Description: 'Cognito User Pool ARN'
    Value: !GetAtt AspireUserPool.Arn
